
package hu.unideb.inf.lasersandmirrors.gui;

import hu.unideb.inf.lasersandmirrors.Controller;
import hu.unideb.inf.lasersandmirrors.DB;
import hu.unideb.inf.lasersandmirrors.Game;
import hu.unideb.inf.lasersandmirrors.Settings;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.ToolTipManager;

/**
 * Szerkesztő menü.
 *
 * @author Kerekes Zoltán
 */
public class EditMenu extends javax.swing.JPanel implements GameMenu {

	/**
	 * Creates new form EditMenu.
	 */
	@SuppressWarnings("unchecked")
	public EditMenu() {
		initComponents();
		
		// A kezdeti állapotban ne tudjuk betölteni a semmit
		editButton.setEnabled(false);
		
		// tooltip
		levelsTitleLabel.setToolTipText(
				"<html>"
					+ "<p style=\"margin-bottom:7px\">"
						+ "<strong>Numbers in brackets:</strong> Lasers, Mirrors and Diamonds on the level."
					+ "</p>"
				+ "</html>");
		ToolTipManager tooltipManager = ToolTipManager.sharedInstance();
		tooltipManager.setInitialDelay(0);
		tooltipManager.setDismissDelay(15_000);

		// listaelemek módosíthatóvá tétele
		levelsListItems = new DefaultListModel<>();
		levelsList.setModel(levelsListItems);
		
		// listaelemek legyártása
		List<DB.LevelInfo> levelInfos = DB.loadLevelInfos();
		if(levelInfos != null){
			for (DB.LevelInfo levelInfo : levelInfos) {
				levelsListItems.addElement(new ListItem(levelInfo.name, String.format("%s (%s, %s, %s)", 
						levelInfo.name,
						levelInfo.laserCount, 
						levelInfo.mirrorCount, 
						levelInfo.diamondCount)));
			}
		}
		levelsListItems.add(0, new ListItem(null, Settings.EMPTY_LIST_ITEM_STRING));
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        levelsContainer = new javax.swing.JPanel();
        levelsTitleLabel = new javax.swing.JLabel();
        levelsListScrollPane = new javax.swing.JScrollPane();
        levelsList = new javax.swing.JList();
        saveContainer = new javax.swing.JPanel();
        editButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        goBackButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(227, 227, 227));
        setName("editMenu"); // NOI18N
        setPreferredSize(new java.awt.Dimension(224, 650));

        titleLabel.setBackground(new java.awt.Color(102, 102, 102));
        titleLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("Edit Menu");

        levelsContainer.setOpaque(false);

        levelsTitleLabel.setText("Existing levels");

        levelsList.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        levelsList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        levelsList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        levelsList.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        levelsList.setDoubleBuffered(true);
        levelsList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                levelsListValueChanged(evt);
            }
        });
        levelsListScrollPane.setViewportView(levelsList);

        javax.swing.GroupLayout levelsContainerLayout = new javax.swing.GroupLayout(levelsContainer);
        levelsContainer.setLayout(levelsContainerLayout);
        levelsContainerLayout.setHorizontalGroup(
            levelsContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(levelsListScrollPane)
            .addComponent(levelsTitleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        levelsContainerLayout.setVerticalGroup(
            levelsContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(levelsContainerLayout.createSequentialGroup()
                .addComponent(levelsTitleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(levelsListScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE))
        );

        saveContainer.setOpaque(false);

        editButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        editButton.setText("Edit");
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        saveButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout saveContainerLayout = new javax.swing.GroupLayout(saveContainer);
        saveContainer.setLayout(saveContainerLayout);
        saveContainerLayout.setHorizontalGroup(
            saveContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(saveContainerLayout.createSequentialGroup()
                .addComponent(editButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        saveContainerLayout.setVerticalGroup(
            saveContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(saveButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(editButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        goBackButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        goBackButton.setForeground(new java.awt.Color(155, 25, 25));
        goBackButton.setText("Main Menu");
        goBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goBackButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(levelsContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(titleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                    .addComponent(goBackButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(saveContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel)
                .addGap(18, 18, 18)
                .addComponent(levelsContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(saveContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 316, Short.MAX_VALUE)
                .addComponent(goBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

	/**
	 * A kilépés gombot megnyomjuk: visszalép a főmenübe.
	 * 
	 * @param evt A kiváltó esemény.
	 */
    private void goBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goBackButtonActionPerformed
        goBack();
    }//GEN-LAST:event_goBackButtonActionPerformed

	/**
	 * A Play gombot megnyomjuk: betöltia  kijelölt pályát a játék.
	 * 
	 * @param evt A kiváltó esemény.
	 */
    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
		String levelName = ((ListItem)levelsList.getSelectedValue()).getValue();
		if(levelName == null){
			Controller.startNewLevel(null);
		} else{
			Controller.loadLevel(levelName);
		}
    }//GEN-LAST:event_editButtonActionPerformed

	/**
	 * Betölti a pályát szerkesztésre vagy csak átlép a szerkesztő menübe.
	 * 
	 * <strong>Még nincs implementálva a szerkesztő.</strong>
	 * 
	 * @param evt A kiváltó esemény.
	 */
    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO: save button
    }//GEN-LAST:event_saveButtonActionPerformed

	/**
	 * A listában kijelöltünk valamit: a Play gomb elszürkülhet, 
	 * mert az új (szerkesztésnek fenntartott) üres páylát nem tölthetjük be.
	 * 
	 * @param evt A kiváltó esemény.
	 */
    private void levelsListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_levelsListValueChanged
		JList list = (JList)evt.getSource();
		editButton.setEnabled(list.getSelectedIndex() != -1);
    }//GEN-LAST:event_levelsListValueChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton editButton;
    private javax.swing.JButton goBackButton;
    private javax.swing.JPanel levelsContainer;
    private javax.swing.JList levelsList;
    private javax.swing.JScrollPane levelsListScrollPane;
    private javax.swing.JLabel levelsTitleLabel;
    private javax.swing.JButton saveButton;
    private javax.swing.JPanel saveContainer;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables

	/**
	 * A listaelemek, melyeket a lista létezésekor is tudunk szerkeszteni.
	 */
	private DefaultListModel<ListItem> levelsListItems;
	
	/**
	 * A pályaválasztó menü elemei kérdezhető le.
	 * 
	 * @return A pályaválasztó menü elemei.
	 */
	public DefaultListModel<ListItem> getLevelsListItems(){
		return this.levelsListItems;
	}
	
	/**
	 * Frissíti a felületet aszerint, hogy teljesíthető-e az aktuális pálya.
	 * 
	 * @param status Teljesíthető az aktuális pálya?
	 */
	public void updateByGameAchieveableStatus(boolean status){
		saveButton.setEnabled(status);
	}

	@Override
	public void goBack() {
		Controller.startNewLevel(null);
		Game.frame.setGameArea(new WelcomeArea());
		Game.frame.setMenu(new MainMenu());
	}
}
