/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package hu.unideb.inf.lasersandmirrors.gui;

import hu.unideb.inf.lasersandmirrors.Controller;
import hu.unideb.inf.lasersandmirrors.DB;
import hu.unideb.inf.lasersandmirrors.Settings;
import java.util.Map;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.ToolTipManager;

/**
 *
 * @author KZ
 */
public class LevelLoaderPanel extends javax.swing.JPanel {

	class ListItem{
		private String name;
		private String extraString;

		public ListItem(String name, String extraString) {
			this.name = name;
			this.extraString = extraString;
		}
		
		public String getName(){
			return name;
		}

		@Override
		public String toString() {
			StringBuilder sb = new StringBuilder(name);
			if(extraString != null){
				sb.append(extraString);
			}
			return sb.toString();
		}
	}
	
	/**
	 * Creates new form LevelLoaderPanel.
	 */
	@SuppressWarnings("unchecked")
	public LevelLoaderPanel() {
		initComponents();
		
		// tooltip
		listTitleLabel.setToolTipText("Numbers in brackets means: Lasers, Mirrors and Diamonds on the level.");
		ToolTipManager tooltipManager = ToolTipManager.sharedInstance();
		tooltipManager.setInitialDelay(0);
		tooltipManager.setDismissDelay(15_000);
		// PENDING: v0.2: Editor
		editButton.setToolTipText("Not yet supported!");
		editButton.setEnabled(false);
		
		// listaelemek módosíthatóvá tétele
		levelsListItems = new DefaultListModel<>();
		levelsList.setModel(levelsListItems);
		Map<String, DB.LevelObjectCounts> levelObjectCountsMap = DB.loadLevelInfos();
		
		// listaelemek legyártása
		if(levelObjectCountsMap != null){
			for (String levelName : levelObjectCountsMap.keySet()) {
				DB.LevelObjectCounts levelObjectCounts = levelObjectCountsMap.get(levelName);
				levelsListItems.addElement(new ListItem(levelName, String.format(" (%s, %s, %s)", 
						levelObjectCounts.laserCount, 
						levelObjectCounts.mirrorCount, 
						levelObjectCounts.diamondCount)));
			}
		}
		levelsListItems.add(0, new ListItem(Settings.EMPTY_LIST_ITEM_STRING, null));
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        levelsPanel = new javax.swing.JPanel();
        listTitleLabel = new javax.swing.JLabel();
        levelsListScrolPane = new javax.swing.JScrollPane();
        levelsList = new javax.swing.JList();
        editButton = new javax.swing.JButton();
        playButton = new javax.swing.JButton();
        exitGameButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(227, 227, 227));
        setPreferredSize(new java.awt.Dimension(224, 650));

        titleLabel.setBackground(new java.awt.Color(102, 102, 102));
        titleLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("Main menu");

        levelsPanel.setOpaque(false);

        listTitleLabel.setText("Available levels");

        levelsList.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        levelsList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        levelsList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        levelsList.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        levelsList.setDoubleBuffered(true);
        levelsList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                levelsListValueChanged(evt);
            }
        });
        levelsListScrolPane.setViewportView(levelsList);

        javax.swing.GroupLayout levelsPanelLayout = new javax.swing.GroupLayout(levelsPanel);
        levelsPanel.setLayout(levelsPanelLayout);
        levelsPanelLayout.setHorizontalGroup(
            levelsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(levelsListScrolPane)
            .addComponent(listTitleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        levelsPanelLayout.setVerticalGroup(
            levelsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(levelsPanelLayout.createSequentialGroup()
                .addComponent(listTitleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(levelsListScrolPane, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE))
        );

        editButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        editButton.setText("Edit");
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        playButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        playButton.setText("Play");
        playButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playButtonActionPerformed(evt);
            }
        });

        exitGameButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        exitGameButton.setForeground(new java.awt.Color(155, 25, 25));
        exitGameButton.setText("Exit Game");
        exitGameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitGameButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(levelsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(titleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(exitGameButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(playButton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                        .addComponent(editButton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel)
                .addGap(18, 18, 18)
                .addComponent(levelsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(playButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 297, Short.MAX_VALUE)
                .addComponent(exitGameButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void exitGameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitGameButtonActionPerformed
        Controller.exitGame();
    }//GEN-LAST:event_exitGameButtonActionPerformed

    private void playButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playButtonActionPerformed
		Controller.loadLevel( ((ListItem)levelsList.getSelectedValue()).getName() );
    }//GEN-LAST:event_playButtonActionPerformed

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        // TODO: Edit button
    }//GEN-LAST:event_editButtonActionPerformed

    private void levelsListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_levelsListValueChanged
		JList list = (JList)evt.getSource();
		String value = ((ListItem)list.getSelectedValue()).getName();
		if(value.equals(Settings.EMPTY_LIST_ITEM_STRING)){
			playButton.setEnabled(false);
		} else {
			playButton.setEnabled(true);
		}
    }//GEN-LAST:event_levelsListValueChanged

	DefaultListModel<ListItem> levelsListItems;
	
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton editButton;
    private javax.swing.JButton exitGameButton;
    private javax.swing.JList levelsList;
    private javax.swing.JScrollPane levelsListScrolPane;
    private javax.swing.JPanel levelsPanel;
    private javax.swing.JLabel listTitleLabel;
    private javax.swing.JButton playButton;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
