
package hu.unideb.inf.lasersandmirrors.gui;

import java.awt.Graphics;
import hu.unideb.inf.lasersandmirrors.Renderer;
import hu.unideb.inf.lasersandmirrors.Settings;

/**
 *
 * @author Kerekes Zoltán
 */
public class PlaygroundPanel extends javax.swing.JPanel {

	/**
	 * Creates new form PlaygroundPanel.
	 */
	public PlaygroundPanel() {
		initComponents();
	}
	
	@Override 
	public void paint(Graphics graphics){
		Renderer.renderGame(graphics, this);
	}
	
	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(800, 650));
        setMinimumSize(new java.awt.Dimension(800, 650));
        setName("playgroundPanel"); // NOI18N
        setPreferredSize(new java.awt.Dimension(800, 650));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
